\documentclass{book}

\usepackage{natbib,amsmath,amsthm}


%% Commands
\newcommand{\I}{\mbox{I}}
\newcommand{\ypred}{\tilde{y}}


% Distributions
\newcommand{\Ber}{\mbox{Ber}}
\newcommand{\Beta}{\mbox{Be}}
\newcommand{\Unif}{\mbox{Unif}}


\newtheorem{example}{Example}

\begin{document}

\include{chapter00}
%\include{chapter01}
%\include{chapter02}

\bibliographystyle{plain}
\bibliography{bib}

\end{document}
