\documentclass[handout,xcolor=pdftex,dvipsnames,table]{beamer} % for handouts
%\documentclass{beamer}


\usecolortheme[RGB={0,0,144}]{structure}
\usetheme{AnnArbor}\usecolortheme{beaver}
%\usetheme{CambridgeUS}\usecolortheme{crane}

\usepackage{verbatim,xmpmulti,color,multicol,multirow,tikz}
\setlength{\unitlength}{\textwidth}  % measure in textwidths
\usepackage[normalem]{ulem}

%\usepackage{beamerthemesplit}
\setbeamertemplate{navigation symbols}{}
%\setbeamercolor{alerted text}{fg=red}
%\setbeamertemplate{block body theorem}{bg=orange}
\setkeys{Gin}{width=0.6\textwidth}


\title{Hierarchical linear models}
\author[Jarad Niemi]{Dr. Jarad Niemi}
\institute[Iowa State]{Iowa State University}
\date{\today}

\newcommand{\mG}{\mathrm{\Gamma}}
\newcommand{\I}{\mathrm{I}}
\newcommand{\mySigma}{\mathrm{\Sigma}}


\begin{document}

%\section{Temp??} \begin{comment}

<<chunk_options, echo=FALSE, message=FALSE>>=
library(knitr) # only needed so the following command does not fail when sourcing R code
opts_chunk$set(fig.width=6, fig.height=5, out.width='.8\\linewidth', fig.align='center', size='tiny')
##############################################
# Hierarchical linear models                 #
##############################################
library(reshape2)
library(plyr)
library(ggplot2)
library(rstan)
library(lme4)
set.seed(20140415)
@

\frame{\maketitle}


\section{Mixed-effect models}
\subsection{Notation}
\frame{\frametitle{Notation}
  Standard notation for mixed-effect models:
	\[ y = X\beta + Zu + e \]
	\pause where 
	\begin{itemize}[<+->]
	\item $y$ is an $n\times 1$ response vector
	\item $X$ is an $n\times p$ design matrix for fixed effects
	\item $\beta$ is a $p\times 1$ unknown fixed effect parameter vector
	\item $Z$ is an $n\times q$ design matrix for random effects
	\item $u$ is a $q\times 1$ unknown random effect parameter vector
	\item $e$ is an $n\times 1$ unknown error vector
	\end{itemize}
}

\subsection{Assumptions}
\frame{\frametitle{Assumptions}

	\[ y = X\beta + Zu + e \]
	Typically assume \pause 
	\begin{itemize} 
	\item $E[u] = E[e] = 0$ \pause 
	\item $V[u] = G$ \pause and $V[e] = R$ \pause 
	\item $Cov[u,e] = 0$ \pause 
	\end{itemize}
	These assumptions imply
	\begin{itemize}
	\item $E[y] = X\beta$ \pause 
	\item $V[y] = ZGZ'+R = \mySigma_y$ \pause
	\end{itemize}
	
	Common addition assumptions
	\begin{itemize}
	\item $V[e] = R = \sigma^2_e \I$, \pause 
	\item $V[u] = G = \mbox{diag}\{ \sigma^2_{u,\cdot} \}$, \pause (or $V[u] = G = \sigma^2_u \I$ for single source), \pause and
	\item $u$ and $e$ are normally distributed.
	\end{itemize}
}

\frame{\frametitle{Rewrite as a standard linear regression model}
	We can rewrite 
	\[ y = X\beta + Zu + e \]
	\pause as 
	\[ y = \tilde{X} \tilde{\beta} + e \]
	\pause where $\tilde{X}$ is $n\times (p+q)$ \pause with
	\[ \tilde{X} = [X\,\, Z] \]
	\pause and $\tilde{\beta}$ is a $(p+q) \times 1$ vector \pause with
	\[ \tilde{\beta} = \left[ \begin{array}{cc} \beta \\ u \end{array} \right]. \]
	\pause The fixed and random effects have been concatenated into the same vector.
}

\section{Hierarchical linear model}
\frame{\frametitle{Hierarchical linear model}
	Assume $y\sim N(\tilde{X} \tilde{\beta}, R)$. \pause A Bayesian analysis proceeds by assigning prior distributions to $\tilde{\beta}$ and $R$. \pause In constructing the prior for $\tilde{\beta}$, consider the components $\beta$ and $u$ separately. \pause Assume
	 \[ \beta \sim N(\beta_0, \mySigma_\beta) \qquad \mbox{and} \qquad u \sim N(0,G) \]
	 independently. 
	 
	 \vspace{0.2in} \pause
	 
	 For the 
	 \begin{itemize}
	 \item {\bf fixed} effects $\beta$, we select $\beta_0$ and $\mySigma_\beta$ \pause while for the
	 \item {\bf random} effects $u$, we assign a prior for $G$.  \pause
	 \end{itemize} 
	 Therefore we have created a hierarchical model for the random effects and thus refer to this as a \emph{hierarchical linear model}.
}

\section{Summary}
\frame{\frametitle{Summary}
	These models are referred to as 
	\begin{itemize}
	\item mixed-effect models, \pause
	\item hierarchical linear models, \pause or
	\item multi-level models.
	\end{itemize}
	
	\vspace{0.2in} \pause 
	
	The parameters for the prior distribution \pause for the
	\begin{itemize}
	\item  fixed effects are not learned \pause and
	\item  random effects are learned.
	\end{itemize}
	
	\vspace{0.2in} \pause  
	
	This corresponds to a non-Bayesian analysis learning a variance parameter for random effects. 
}



\section{Seedling weight example}
\frame{\frametitle{Seedling weight example}
  Example taken from Dan Nettleton:
	\begin{quote}
	Researchers were interested in comparing the dry
weight of maize seedlings from two different genotypes (A and B).
For each genotype, nine seeds were planted in each of
four trays. The eight trays in total were randomly
positioned in a growth chamber. Three weeks after the
emergence of the first seedling, emerged seedlings were
harvested from each tray and, after drying, weighed. 
	\end{quote}
	Assume the missing data (emergence) mechanism is ignorable. 
}

\frame{\frametitle{A picture}
\setkeys{Gin}{width=\textwidth}

	\vspace{-0.2in}

	\begin{center}
	\includegraphics[page=4]{19AitkenExample}
	\end{center}
}

\subsection{Model}
\frame{\frametitle{A model}
	Let $y_{ijk}$ be the weight \pause of the 
	\begin{itemize}
	\item $i^{th}$ genotype with $i=1,2$, \pause
	\item $j^{th}$ tray $j=1,2,3,4$, \pause and 
	\item $k^{th}$ seedling with $k=1,\ldots,n_{ij}$.
	\end{itemize}
	Then, we assume 
	\[ y_{ijk} = \mu + \gamma_i + \tau_{ij} + e_{ijk} \]
	\pause where 
	\begin{itemize}
	\item $\tau_{ij} \stackrel{iid}{\sim} N(0,\sigma^2_\tau)$ \pause and, independently,
	\item $e_{ijk} \stackrel{iid}{\sim} N(0,\sigma^2_e)$. 
	\end{itemize}
}

\frame{\frametitle{As a general mixed effects model}
	Let $X$ have the following 3 columns \pause
	\begin{itemize}
	\item col1: all ones (intercept) [$\mu$] \pause 
	\item col2: ones if genotype A and zeros otherwise [$\gamma_1$] \pause
	\item col3: ones if genotype B and zeros otherwise [$\gamma_2$] \pause
	\end{itemize}
	Let $Z$ have the following 8 columns \pause 
	\begin{itemize}
	\item col1: ones if genotype 1, tray 1 and zeros otherwise [$\tau_{11}$] \pause
	\item col2: ones if genotype 1, tray 2 and zeros otherwise [$\tau_{12}$] \pause
	\item $\vdots$ \pause
	\item col8: ones if genotype 2, tray 4 and zeros otherwise [$\tau_{24}$] \pause
	\end{itemize}
	Then 
	\[ y = X\beta + Zu + e \] 
	\pause with $u\sim N(0,\sigma^2_\tau\I)$ and, independently, $e\sim N(0,\sigma^2_e\I)$. 
}

\frame{\frametitle{Model construction for BUGS/JAGS}
	An alternative construction of the model convenient for programming in BUGS/JAGS \pause uses the notation
	\begin{itemize}
	\item $y_i$ is the weight for seedling $i$ with $i=1,\ldots,n$ \pause 
	\item $g[i]\in \{1,2\}$ is the genotype for seedling $i$  \pause
	\item $t[i]\in\{1,2,\ldots,8\}$ is the {\bf unique} tray id for seedling $i$
	\end{itemize}
	
	\vspace{0.2in} \pause 
	
	Then the model is 
	\[ y_i = \mu + \gamma_{g[i]} + \tau_{t[i]} + e_i \] 
	\pause with $e_i \stackrel{iid}{\sim} N(0,\sigma^2_e)$ and, independently, $\tau_t \stackrel{iid}{\sim} N(0,\sigma^2_\tau)$ with $t=1,\ldots,8$.
}

\subsection{Summary}
\frame{\frametitle{Summary}
	General mixed-effect models
	\begin{itemize}
	\item $y = X\beta + Zu + e, u\sim N(0,G), e\sim N(0,R)$ \pause
	\item $y = \tilde{X} \tilde{\beta} + e, \tilde{\beta}\sim N(\tilde{\beta}_0, \mySigma_{\tilde{\beta}}), e\sim N(0,R)$ 
	\end{itemize}
	
	\vspace{0.2in} \pause
	
	The particular example in this mini-lecture:
	\begin{itemize}
	\item $y_{ijk} = \mu + \gamma_i + \tau_{ij} + e_{ijk}, \tau_{ij} \stackrel{iid}{\sim} N(0,\sigma^2_\tau), e_{ijk} \stackrel{iid}{\sim} N(0,\sigma^2_e)$ \pause
	\item $y_i = \mu + \gamma_{g[i]} + \tau_{t[i]} + e_i, \tau_t \stackrel{iid}{\sim} N(0,\sigma^2_\tau), e_i \stackrel{iid}{\sim} N(0,\sigma^2_e) $  \pause
	\item $y = X\beta + Zu + e, u\sim N(0,\sigma^2_\tau\I), e\sim N(0,\sigma_e^2\I) $ \pause
	\item $y = \tilde{X} \tilde{\beta} + e, \tilde{X} = [X\,\, Z], \tilde{\beta} = (\beta' \,\, u')'$ \pause
	
	$\tilde{\beta}\sim N([\beta_0 \,\, 0]', \mbox{bdiag} \{ \mySigma_{\beta}, \sigma^2_\tau \I \}), e\sim N(0,\sigma_e^2\I)$ 
	\end{itemize}
}


\section{Seedling weight example}
\frame{\frametitle{Seedling weight example}
\setkeys{Gin}{width=0.6\textwidth}
  Example taken from Dan Nettleton:
	{\tiny
	\begin{quote}
	Researchers were interested in comparing the dry
weight of maize seedlings from two different genotypes (A and B).
For each genotype, nine seeds were planted in each of
four trays. The eight trays in total were randomly
positioned in a growth chamber. Three weeks after the
emergence of the first seedling, emerged seedlings were
harvested from each tray and, after drying, weighed. 
	\end{quote}}

	\vspace{-0.2in}

	\begin{center}
	\includegraphics[page=4]{19AitkenExample}
	\end{center}

	\vspace{-0.2in} \pause
	
	Of primary interest is the difference in seedling weights for the two species. \pause 
  
  Data: {\tiny \url{http://www.public.iastate.edu/~dnett/S511/SeedlingDryWeight2.txt}}
}

\subsection{Mixed-effects model}
\frame{\frametitle{Model construction for BUGS/JAGS}
	An alternative construction of the model convenient for programming in BUGS/JAGS \pause uses the notation
	\begin{itemize}
	\item $y_i$ is the weight for seedling $i$ with $i=1,\ldots,n$ \pause 
	\item $g[i]\in \{1,2\}$ is the genotype for seedling $i$  \pause
	\item $t[i]\in\{1,2,\ldots,8\}$ is the tray id for seedling $i$
	\end{itemize}
	
	\vspace{0.2in} \pause 
	
	Then the model is 
	\[ y_i = \gamma_{g[i]} + \tau_{t[i]} + e_i \] 
	\pause with $e_i \stackrel{iid}{\sim} N(0,\sigma^2_e)$ and, independently, $\tau_t \stackrel{iid}{\sim} N(0,\sigma^2_\tau)$ with $t=1,\ldots,8$.
	
	\vspace{0.2in} \pause
	
	$\gamma_1-\gamma_2$ is the quantity of interet.
}

\begin{frame}[fragile]
<<data>>=
d = read.table("SeedlingDryWeight2.txt", header=TRUE)

summary(d)
@
\end{frame}

\begin{frame}[fragile]
<<non-Bayesian, message=FALSE, cache=TRUE>>=
m1 = lmer(SeedlingWeight ~ Genotype + (1|Tray), d)
summary(m1)
@
Why no pvalues? {\tiny \url{https://stat.ethz.ch/pipermail/r-help/2006-May/094765.html}}
\end{frame}



\begin{frame}
From \url{https://stat.ethz.ch/pipermail/r-help/2006-May/094765.html} (19 May 2006):
{\small 
\begin{quote}
Users are often surprised and alarmed that the summary of a linear
mixed model fit by lmer provides estimates of the fixed-effects
parameters, standard errors for these parameters and a t-ratio but no
p-values.  

...

Most of the research on tests for the fixed-effects specification in a
mixed model begin with the assumption that these statistics will have
an F distribution with a known numerator degrees of freedom and the
only purpose of the research is to decide how to obtain an approximate
denominator degrees of freedom.  I don't agree.

...

For the time being, I would recommend using a Markov Chain Monte Carlo
sample (function mcmcsamp) to evaluate the properties of individual
coefficients (use HPDinterval or just summary from the "coda"
package).  
\end{quote}}
\end{frame}


\begin{frame}[fragile]
<<confint_merMod_help>>=
help("confint.merMod", help_type="text")
@
\end{frame}


\begin{frame}[fragile]
<<confidence_intervals, dependson="non-Bayesian", cache=TRUE>>=
confint(m1, method="profile")
confint(m1, method="Wald")
confint(m1, method="boot")
@
\end{frame}


\subsection{Stan code}
\begin{frame}[fragile]
<<stan_model, tidy=FALSE, cache=TRUE>>=
stan_model = "
data {
  int<lower=1> n;
  int<lower=1> n_genotypes;
  int<lower=1> n_trays;

  real y[n];
  int genotype[n];
  int tray[n];
}
parameters {
  real gamma[n_genotypes]; // Implicit prior over whole real line
  real tau[n_trays];
  real<lower=0> sigma_e;
  real<lower=0> sigma_tau;
}

model {
  for (i in 1:n) {
    y[i] ~ normal(gamma[genotype[i]]+tau[tray[i]], sigma_e);
  }
 
  # Random effects
  for (t in 1:n_trays) { tau[t]   ~ normal(0, sigma_tau); }
}

generated quantities {
  real diff;
  diff <- gamma[2] - gamma[1];
}
"
@
\end{frame}

\subsection{Results}
\begin{frame}[fragile]
<<analysis, dependson="stan_model", cache=TRUE>>=
m = stan_model(model_code=stan_model)

dat = list(y        = d$SeedlingWeight, 
           genotype = as.numeric(d$Genotype),
           tray     = d$Tray, 
           n           = nrow(d),
           n_genotypes = nlevels(d$Genotype),
           n_trays     = max(d$Tray))

r = sampling(m, dat, c("gamma","tau","sigma_e","sigma_tau","diff"))
@
\end{frame}

\begin{frame}[fragile]
<<table, dependson="analysis">>=
r
@
\end{frame}



\begin{frame}[fragile]
<<table, dependson="analysis">>=
plot(r)
@
\end{frame}



\subsection{Summary}
\frame{\frametitle{Summary}
	Demonstrated
	\begin{itemize}
	\item a simple mixed effect model analysis \pause
	\item ease of BUGS/JAGS coding \pause 
	\item similarity to non-Bayesian estimates \pause
	\item ease of interpreting output
	\end{itemize}
}





\end{document}