\documentclass[handout,xcolor=pdftex,dvipsnames,table]{beamer} % for handouts
%\documentclass{beamer}


\usecolortheme[RGB={0,0,144}]{structure}
\usetheme{AnnArbor}\usecolortheme{beaver}
%\usetheme{CambridgeUS}\usecolortheme{crane}

\usepackage{verbatim,xmpmulti,color,multicol,multirow,tikz,animate}
\setlength{\unitlength}{\textwidth}  % measure in textwidths
\usepackage[normalem]{ulem}

%\usepackage{beamerthemesplit}
\setbeamertemplate{navigation symbols}{}
%\setbeamercolor{alerted text}{fg=red}
%\setbeamertemplate{block body theorem}{bg=orange}
\setkeys{Gin}{width=0.6\textwidth}


\title{{Hierarchical linear models}
\author[Jarad Niemi]{Dr. Jarad Niemi}
\institute[Iowa State]{Iowa State University}
\date{\today}

\newcommand{\mG}{\mathrm{\Gamma}}
\newcommand{\I}{\mathrm{I}}
\newcommand{\mySigma}{\mathrm{\Sigma}}


\begin{document}

%\section{Temp??} \begin{comment}

<<chunk_options, echo=FALSE, message=FALSE>>=
library(knitr) # only needed so the following command does not fail when sourcing R code
opts_chunk$set(fig.width=6, fig.height=5, out.width='.8\\linewidth', fig.align='center', size='tiny')
##############################################
# Hierarchical linear models                 #
##############################################
library(reshape2)
library(plyr)
library(ggplot2)
library(rjags)
library(rstan)
set.seed(20140415)
@

\frame{\maketitle}


\section{Mixed-effect models}
\subsection{Notation}
\frame{\frametitle{Notation}
  Standard notation for mixed-effect models:
	\[ y = X\beta + Zu + e \]
	\pause where 
	\begin{itemize}[<+->]
	\item $y$ is an $n\times 1$ response vector
	\item $X$ is an $n\times p$ design matrix for fixed effects
	\item $\beta$ is a $p\times 1$ unknown fixed effect parameter vector
	\item $Z$ is an $n\times q$ design matrix for random effects
	\item $u$ is a $q\times 1$ unknown random effect parameter vector
	\item $e$ is an $n\times 1$ unknown error vector
	\end{itemize}
}

\subsection{Assumptions}
\frame{\frametitle{Assumptions}

	\[ y = X\beta + Zu + e \]
	Typically assume \pause 
	\begin{itemize} 
	\item $E[u] = E[e] = 0$ \pause 
	\item $V[u] = G$ \pause and $V[e] = R$ \pause 
	\item $Cov[u,e] = 0$ \pause 
	\end{itemize}
	These assumptions imply
	\begin{itemize}
	\item $E[y] = X\beta$ \pause 
	\item $V[y] = ZGZ'+R = \mySigma_y$ \pause
	\end{itemize}
	
	Common addition assumptions
	\begin{itemize}
	\item $V[e] = R = \sigma^2_e \I$, \pause 
	\item $V[u] = G = \mbox{diag}\{ \sigma^2_{u,\cdot} \}$, \pause (or $V[u] = G = \sigma^2_u \I$ for single source), \pause and
	\item $u$ and $e$ are normally distributed.
	\end{itemize}
}

\frame{\frametitle{Rewrite as a standard linear regression model}
	We can rewrite 
	\[ y = X\beta + Zu + e \]
	\pause as 
	\[ y = \tilde{X} \tilde{\beta} + e \]
	\pause where $\tilde{X}$ is $n\times (p+q)$ \pause with
	\[ \tilde{X} = [X\,\, Z] \]
	\pause and $\tilde{\beta}$ is a $(p+q) \times 1$ vector \pause with
	\[ \tilde{\beta} = \left[ \begin{array}{cc} \beta \\ u \end{array} \right]. \]
	\pause The fixed and random effects have been concatenated into the same vector.
}

\section{Hierarchical linear model}
\frame{\frametitle{Hierarchical linear model}
	Assume $y\sim N(\tilde{X} \tilde{\beta}, R)$. \pause A Bayesian analysis proceeds by assigning prior distributions to $\tilde{\beta}$ and $R$. \pause In constructing the prior for $\tilde{\beta}$, consider the components $\beta$ and $u$ separately. \pause Assume
	 \[ \beta \sim N(\beta_0, \mySigma_\beta) \qquad \mbox{and} \qquad u \sim N(0,G) \]
	 independently. 
	 
	 \vspace{0.2in} \pause
	 
	 For the 
	 \begin{itemize}
	 \item {\bf fixed} effects $\beta$, we select $\beta_0$ and $\mySigma_\beta$ \pause while for the
	 \item {\bf random} effects $u$, we assign a prior for $G$.  \pause
	 \end{itemize} 
	 Therefore we have created a hierarchical model for the random effects and thus refer to this as a \emph{hierarchical linear model}.
}

\section{Summary}
\frame{\frametitle{Summary}
	These models are referred to as 
	\begin{itemize}
	\item mixed-effect models, \pause
	\item hierarchical linear models, \pause or
	\item multi-level models.
	\end{itemize}
	
	\vspace{0.2in} \pause 
	
	The parameters for the prior distribution \pause for the
	\begin{itemize}
	\item  fixed effects are not learned \pause and
	\item  random effects are learned.
	\end{itemize}
	
	\vspace{0.2in} \pause  
	
	This corresponds to a non-Bayesian analysis learning a variance parameter for random effects. 
}



\section{Seedling weight example}
\frame{\frametitle{Seedling weight example}
  Example taken from Dan Nettleton:
	\begin{quote}
	Researchers were interested in comparing the dry
weight of maize seedlings from two different genotypes (A and B).
For each genotype, nine seeds were planted in each of
four trays. The eight trays in total were randomly
positioned in a growth chamber. Three weeks after the
emergence of the first seedling, emerged seedlings were
harvested from each tray and, after drying, weighed. 
	\end{quote}
	Assume the missing data (emergence) mechanism is ignorable. 
}

\frame{\frametitle{A picture}
\setkeys{Gin}{width=\textwidth}

	\vspace{-0.2in}

	\begin{center}
	\includegraphics[page=4]{19AitkenExample}
	\end{center}
}

\subsection{Model}
\frame{\frametitle{A model}
	Let $y_{ijk}$ be the weight \pause of the 
	\begin{itemize}
	\item $i^{th}$ genotype with $i=1,2$, \pause
	\item $j^{th}$ tray $j=1,2,3,4$, \pause and 
	\item $k^{th}$ seedling with $k=1,\ldots,n_{ij}$.
	\end{itemize}
	Then, we assume 
	\[ y_{ijk} = \mu + \gamma_i + \tau_{ij} + e_{ijk} \]
	\pause where 
	\begin{itemize}
	\item $\tau_{ij} \stackrel{iid}{\sim} N(0,\sigma^2_\tau)$ \pause and, independently,
	\item $e_{ijk} \stackrel{iid}{\sim} N(0,\sigma^2_e)$. 
	\end{itemize}
}

\frame{\frametitle{As a general mixed effects model}
	Let $X$ have the following 3 columns \pause
	\begin{itemize}
	\item col1: all ones (intercept) [$\mu$] \pause 
	\item col2: ones if genotype A and zeros otherwise [$\gamma_1$] \pause
	\item col3: ones if genotype B and zeros otherwise [$\gamma_2$] \pause
	\end{itemize}
	Let $Z$ have the following 8 columns \pause 
	\begin{itemize}
	\item col1: ones if genotype 1, tray 1 and zeros otherwise [$\tau_{11}$] \pause
	\item col2: ones if genotype 1, tray 2 and zeros otherwise [$\tau_{12}$] \pause
	\item $\vdots$ \pause
	\item col8: ones if genotype 2, tray 4 and zeros otherwise [$\tau_{24}$] \pause
	\end{itemize}
	Then 
	\[ y = X\beta + Zu + e \] 
	\pause with $u\sim N(0,\sigma^2_\tau\I)$ and, independently, $e\sim N(0,\sigma^2_e\I)$. 
}

\frame{\frametitle{Model construction for BUGS/JAGS}
	An alternative construction of the model convenient for programming in BUGS/JAGS \pause uses the notation
	\begin{itemize}
	\item $y_i$ is the weight for seedling $i$ with $i=1,\ldots,n$ \pause 
	\item $g[i]\in \{1,2\}$ is the genotype for seedling $i$  \pause
	\item $t[i]\in\{1,2,\ldots,8\}$ is the {\bf unique} tray id for seedling $i$
	\end{itemize}
	
	\vspace{0.2in} \pause 
	
	Then the model is 
	\[ y_i = \mu + \gamma_{g[i]} + \tau_{t[i]} + e_i \] 
	\pause with $e_i \stackrel{iid}{\sim} N(0,\sigma^2_e)$ and, independently, $\tau_t \stackrel{iid}{\sim} N(0,\sigma^2_\tau)$ with $t=1,\ldots,8$.
}

\subsection{Summary}
\frame{\frametitle{Summary}
	General mixed-effect models
	\begin{itemize}
	\item $y = X\beta + Zu + e, u\sim N(0,G), e\sim N(0,R)$ \pause
	\item $y = \tilde{X} \tilde{\beta} + e, \tilde{\beta}\sim N(\tilde{\beta}_0, \mySigma_{\tilde{\beta}}), e\sim N(0,R)$ 
	\end{itemize}
	
	\vspace{0.2in} \pause
	
	The particular example in this mini-lecture:
	\begin{itemize}
	\item $y_{ijk} = \mu + \gamma_i + \tau_{ij} + e_{ijk}, \tau_{ij} \stackrel{iid}{\sim} N(0,\sigma^2_\tau), e_{ijk} \stackrel{iid}{\sim} N(0,\sigma^2_e)$ \pause
	\item $y_i = \mu + \gamma_{g[i]} + \tau_{t[i]} + e_i, \tau_t \stackrel{iid}{\sim} N(0,\sigma^2_\tau), e_i \stackrel{iid}{\sim} N(0,\sigma^2_e) $  \pause
	\item $y = X\beta + Zu + e, u\sim N(0,\sigma^2_\tau\I), e\sim N(0,\sigma_e^2\I) $ \pause
	\item $y = \tilde{X} \tilde{\beta} + e, \tilde{X} = [X\,\, Z], \tilde{\beta} = (\beta' \,\, u')'$ \pause
	
	$\tilde{\beta}\sim N([\beta_0 \,\, 0]', \mbox{bdiag} \{ \mySigma_{\beta}, \sigma^2_\tau \I \}), e\sim N(0,\sigma_e^2\I)$ 
	\end{itemize}
}


\section{Seedling weight example}
\frame{\frametitle{Seedling weight example}
\setkeys{Gin}{width=0.6\textwidth}
  Example taken from Dan Nettleton:
	{\tiny
	\begin{quote}
	Researchers were interested in comparing the dry
weight of maize seedlings from two different genotypes (A and B).
For each genotype, nine seeds were planted in each of
four trays. The eight trays in total were randomly
positioned in a growth chamber. Three weeks after the
emergence of the first seedling, emerged seedlings were
harvested from each tray and, after drying, weighed. 
	\end{quote}}

	\vspace{-0.2in}

	\begin{center}
	\includegraphics[page=4]{19AitkenExample}
	\end{center}

	\vspace{-0.2in} \pause
	
	Of primary interest is the difference in seedling weights for the two species. \pause 
  
  Data: \url{http://www.public.iastate.edu/~dnett/S511/SeedlingDryWeight2.txt}
}

\subsection{Mixed-effects model}
\frame{\frametitle{Model construction for BUGS/JAGS}
	An alternative construction of the model convenient for programming in BUGS/JAGS \pause uses the notation
	\begin{itemize}
	\item $y_i$ is the weight for seedling $i$ with $i=1,\ldots,n$ \pause 
	\item $g[i]\in \{1,2\}$ is the genotype for seedling $i$  \pause
	\item $t[i]\in\{1,2,\ldots,8\}$ is the tray id for seedling $i$
	\end{itemize}
	
	\vspace{0.2in} \pause 
	
	Then the model is 
	\[ y_i = \gamma_{g[i]} + \tau_{t[i]} + e_i \] 
	\pause with $e_i \stackrel{iid}{\sim} N(0,\sigma^2_e)$ and, independently, $\tau_t \stackrel{iid}{\sim} N(0,\sigma^2_\tau)$ with $t=1,\ldots,8$.
	
	\vspace{0.2in} \pause
	
	$\gamma_1-\gamma_2$ is the quantity of interet.
}

\subsection{JAGS code}
\begin{frame}[fragile]
<<analysis, tidy=FALSE>>=
d = read.table("SeedlingDryWeight2.txt", header=TRUE)

model = "
model {
  for (i in 1:n) {
    y[i] ~ dnorm(gamma[genotype[i]]+tau[tray[i]], eta.e)
  }

  # Fixed effects
  for (g in 1:ng) { gamma[g] ~ dnorm(0,eta.gamma) }
 
  # Random effects
  for (t in 1:nt) { tau[t]   ~ dnorm(0,eta.tau  ) }
  
  # Other priors
  eta.e   <- 1/sigma.e^2
  eta.tau <- 1/sigma.tau^2

  sigma.e   ~ dunif(0,1000)
  sigma.tau ~ dunif(0,1000)

  # Quantity of interest
  diff <- gamma[1] - gamma[2]
}
"
@
\end{frame}

\subsection{Results}
\frame[containsverbatim]{\frametitle{Results}
{\tiny 
\begin{verbatim}
dat = list(y = d$SeedlingWeight, 
           genotype = as.numeric(d$Genotype),
           tray = d$Tray, n = nrow(d)
           ng = 2,
           nt = max(d$Tray),
           eta.gamma = 1e-6)

m = jags.model(textConnection(model), dat, n.chains=3, n.adapt=10000)

res = coda.samples(m, c("sigma.e","sigma.tau","gamma","tau","diff"), 10000, nthin=10)

gelman.diag(res, mult=F)
# Upper CIs all less than 1.03


round(summary(res)$quantiles,2)




           2.5%   25%   50%   75% 97.5%
diff      -3.86  1.49  3.47  5.41  9.59
gamma[1]  10.04 13.77 15.23 16.59 19.56
gamma[2]   7.14 10.46 11.80 13.10 15.97
sigma.e    1.58  1.79  1.92  2.06  2.39
sigma.tau  2.26  3.20  3.97  5.08  8.99
tau[1]    -9.49 -6.33 -4.89 -3.40  0.26
tau[2]    -1.68  1.28  2.67  4.18  7.99
tau[3]    -5.59 -2.58 -1.16  0.33  4.14
tau[4]    -0.67  2.27  3.64  5.16  8.99
tau[5]    -3.19 -0.20  1.13  2.55  5.93
tau[6]    -6.07 -3.06 -1.74 -0.33  2.97
tau[7]    -1.20  1.69  3.05  4.47  7.82
tau[8]    -7.05 -4.03 -2.69 -1.29  2.04
\end{verbatim}
}
}


\frame[containsverbatim]{\frametitle{Compare to non-Bayesian estimates}
{\tiny 
\begin{verbatim}
> library(lme4)
> m1 = lmer(y ~ genotype + (1|tray), dat)
> summary(m1)
Linear mixed model fit by REML 
Formula: y ~ genotype + (1 | tray) 
   Data: dat 
   AIC   BIC logLik deviance REMLdev
 255.1 263.2 -123.6      253   247.1
Random effects:
 Groups   Name        Variance Std.Dev.
 tray     (Intercept) 11.6612  3.4149  
 Residual              3.5428  1.8822  
Number of obs: 56, groups: tray, 8

Fixed effects:
            Estimate Std. Error t value
(Intercept)   18.839      3.902   4.828
genotype      -3.550      2.468  -1.438
\end{verbatim}


\url{https://stat.ethz.ch/pipermail/r-help/2006-May/094765.html}
}

}

\subsection{Summary}
\frame{\frametitle{Summary}
	Demonstrated
	\begin{itemize}
	\item a simple mixed effect model analysis \pause
	\item ease of BUGS/JAGS coding \pause 
	\item similarity to non-Bayesian estimates \pause
	\item ease of interpreting output
	\end{itemize}
}





\end{document}